server:
  port: 9000
spring:
  application:
    name: MY-APPLICATIONS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jianzhi?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: start
  # 静态文件请求匹配方式
  # 修改默认的静态寻址资源目录
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/mydemo/applications/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      offcn: debug
  file:
    path: D:\log\scw-user
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: offcnludie.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4FymPqmgSd2TN9Gag5CT
  accessKeySecret: ygog7QcQfedLdIWddvrVc8mu4Uj7lk
  bucketName: offcnludie

